openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/login:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: number
                  description: ''
                  example: 501224.49471553
                password:
                  type: string
                  description: ''
                  example: quisquam
              required:
                - phone
                - password
  /api/register:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: multipart/form-data
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'يجب أن يكون حقل value عنوان بريد إلكتروني صحيح البُنية.'
                  example: cody46@example.com
                name:
                  type: string
                  description: ''
                  example: beatae
                phone:
                  type: number
                  description: ''
                  example: 1706.3092
                password:
                  type: string
                  description: ''
                  example: quis
                avatar:
                  type: string
                  format: binary
                  description: 'يجب أن يكون حقل value صورةً.'
                bio:
                  type: string
                  description: ''
                  example: delectus
              required:
                - email
                - phone
                - password
  /api/logout:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
  /api/products/search:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: name
          description: 'to search for in product name .'
          example: null
          required: false
          schema:
            type: string
            description: 'to search for in product name .'
            example: null
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: explicabo
                      image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                      description: 'Placeat eaque consequuntur eius.'
                    -
                      id: 2
                      name: voluptates
                      image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                      description: 'Est repudiandae enim dolorum.'
                  links:
                    first: 'http://127.0.0.1:8000/api/products/search?page=1'
                    last: 'http://127.0.0.1:8000/api/products/search?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; السابق'
                        active: false
                      -
                        url: 'http://127.0.0.1:8000/api/products/search?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'التالي &raquo;'
                        active: false
                    path: 'http://127.0.0.1:8000/api/products/search'
                    per_page: 10
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: explicabo
                        image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                        description: 'Placeat eaque consequuntur eius.'
                      -
                        id: 2
                        name: voluptates
                        image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                        description: 'Est repudiandae enim dolorum.'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: 'http://127.0.0.1:8000/api/products/search?page=1'
                      last: 'http://127.0.0.1:8000/api/products/search?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; السابق'
                          active: false
                        -
                          url: 'http://127.0.0.1:8000/api/products/search?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'التالي &raquo;'
                          active: false
                      path: 'http://127.0.0.1:8000/api/products/search'
                      per_page: 10
                      to: 2
                      total: 2
      tags:
        - Endpoints
  /api/products:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: category_id
          description: 'filter products by category_id field.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'filter products by category_id field.'
            example: 1
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 2
                      name: voluptates
                      image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                      description: 'Est repudiandae enim dolorum.'
                    -
                      id: 1
                      name: explicabo
                      image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                      description: 'Placeat eaque consequuntur eius.'
                  links:
                    first: 'http://127.0.0.1:8000/api/products?page=1'
                    last: 'http://127.0.0.1:8000/api/products?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; السابق'
                        active: false
                      -
                        url: 'http://127.0.0.1:8000/api/products?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'التالي &raquo;'
                        active: false
                    path: 'http://127.0.0.1:8000/api/products'
                    per_page: 10
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 2
                        name: voluptates
                        image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                        description: 'Est repudiandae enim dolorum.'
                      -
                        id: 1
                        name: explicabo
                        image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                        description: 'Placeat eaque consequuntur eius.'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: 'http://127.0.0.1:8000/api/products?page=1'
                      last: 'http://127.0.0.1:8000/api/products?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; السابق'
                          active: false
                        -
                          url: 'http://127.0.0.1:8000/api/products?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'التالي &raquo;'
                          active: false
                      path: 'http://127.0.0.1:8000/api/products'
                      per_page: 10
                      to: 2
                      total: 2
      tags:
        - Endpoints
  '/api/products/{id}':
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    name: explicabo
                    image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                    description: 'Placeat eaque consequuntur eius.'
                    category:
                      id: 1
                      category_id: null
                      image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                      slug: nulla-suscipit-alias-enim-temporibus-dolorum
                      title: esse
                      description: 'Dolore dolor nisi odio repellat modi cupiditate.'
                      meta_description: 'Voluptatem omnis voluptatum quis qui cumque.'
                properties:
                  data:
                    type: object
                    example:
                      id: 1
                      name: explicabo
                      image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                      description: 'Placeat eaque consequuntur eius.'
                      category:
                        id: 1
                        category_id: null
                        image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                        slug: nulla-suscipit-alias-enim-temporibus-dolorum
                        title: esse
                        description: 'Dolore dolor nisi odio repellat modi cupiditate.'
                        meta_description: 'Voluptatem omnis voluptatum quis qui cumque.'
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
  /api/categories/search:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: query
          name: title
          description: 'string to search for in category title .  .'
          example: null
          required: true
          schema:
            type: string
            description: 'string to search for in category title .  .'
            example: null
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      category_id: null
                      image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                      slug: nulla-suscipit-alias-enim-temporibus-dolorum
                      title: esse
                      description: 'Dolore dolor nisi odio repellat modi cupiditate.'
                      meta_description: 'Voluptatem omnis voluptatum quis qui cumque.'
                    -
                      id: 2
                      category_id: null
                      image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                      slug: minus-quidem-magnam-eos-earum-est
                      title: quo
                      description: 'Soluta ea perspiciatis assumenda ipsa.'
                      meta_description: 'Dolor odit neque at laborum eum omnis.'
                  links:
                    first: 'http://127.0.0.1:8000/api/categories/search?page=1'
                    last: 'http://127.0.0.1:8000/api/categories/search?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; السابق'
                        active: false
                      -
                        url: 'http://127.0.0.1:8000/api/categories/search?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'التالي &raquo;'
                        active: false
                    path: 'http://127.0.0.1:8000/api/categories/search'
                    per_page: 10
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        category_id: null
                        image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                        slug: nulla-suscipit-alias-enim-temporibus-dolorum
                        title: esse
                        description: 'Dolore dolor nisi odio repellat modi cupiditate.'
                        meta_description: 'Voluptatem omnis voluptatum quis qui cumque.'
                      -
                        id: 2
                        category_id: null
                        image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                        slug: minus-quidem-magnam-eos-earum-est
                        title: quo
                        description: 'Soluta ea perspiciatis assumenda ipsa.'
                        meta_description: 'Dolor odit neque at laborum eum omnis.'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: 'http://127.0.0.1:8000/api/categories/search?page=1'
                      last: 'http://127.0.0.1:8000/api/categories/search?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; السابق'
                          active: false
                        -
                          url: 'http://127.0.0.1:8000/api/categories/search?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'التالي &raquo;'
                          active: false
                      path: 'http://127.0.0.1:8000/api/categories/search'
                      per_page: 10
                      to: 2
                      total: 2
      tags:
        - Endpoints
  /api/categories:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 2
                      category_id: null
                      image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                      slug: minus-quidem-magnam-eos-earum-est
                      title: quo
                      description: 'Soluta ea perspiciatis assumenda ipsa.'
                      meta_description: 'Dolor odit neque at laborum eum omnis.'
                    -
                      id: 1
                      category_id: null
                      image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                      slug: nulla-suscipit-alias-enim-temporibus-dolorum
                      title: esse
                      description: 'Dolore dolor nisi odio repellat modi cupiditate.'
                      meta_description: 'Voluptatem omnis voluptatum quis qui cumque.'
                  links:
                    first: 'http://127.0.0.1:8000/api/categories?page=1'
                    last: 'http://127.0.0.1:8000/api/categories?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; السابق'
                        active: false
                      -
                        url: 'http://127.0.0.1:8000/api/categories?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'التالي &raquo;'
                        active: false
                    path: 'http://127.0.0.1:8000/api/categories'
                    per_page: 10
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 2
                        category_id: null
                        image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                        slug: minus-quidem-magnam-eos-earum-est
                        title: quo
                        description: 'Soluta ea perspiciatis assumenda ipsa.'
                        meta_description: 'Dolor odit neque at laborum eum omnis.'
                      -
                        id: 1
                        category_id: null
                        image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                        slug: nulla-suscipit-alias-enim-temporibus-dolorum
                        title: esse
                        description: 'Dolore dolor nisi odio repellat modi cupiditate.'
                        meta_description: 'Voluptatem omnis voluptatum quis qui cumque.'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: 'http://127.0.0.1:8000/api/categories?page=1'
                      last: 'http://127.0.0.1:8000/api/categories?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; السابق'
                          active: false
                        -
                          url: 'http://127.0.0.1:8000/api/categories?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'التالي &raquo;'
                          active: false
                      path: 'http://127.0.0.1:8000/api/categories'
                      per_page: 10
                      to: 2
                      total: 2
      tags:
        - Endpoints
  '/api/categories/{id}':
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    category_id: null
                    image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                    slug: nulla-suscipit-alias-enim-temporibus-dolorum
                    title: esse
                    description: 'Dolore dolor nisi odio repellat modi cupiditate.'
                    meta_description: 'Voluptatem omnis voluptatum quis qui cumque.'
                    products:
                      -
                        id: 1
                        name: explicabo
                        image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                        description: 'Placeat eaque consequuntur eius.'
                      -
                        id: 2
                        name: voluptates
                        image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                        description: 'Est repudiandae enim dolorum.'
                properties:
                  data:
                    type: object
                    example:
                      id: 1
                      category_id: null
                      image: 'http://127.0.0.1:8000/storage/uploads/categories/http://127.0.0.1:8000/images/default/image.jpg'
                      slug: nulla-suscipit-alias-enim-temporibus-dolorum
                      title: esse
                      description: 'Dolore dolor nisi odio repellat modi cupiditate.'
                      meta_description: 'Voluptatem omnis voluptatum quis qui cumque.'
                      products:
                        -
                          id: 1
                          name: explicabo
                          image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                          description: 'Placeat eaque consequuntur eius.'
                        -
                          id: 2
                          name: voluptates
                          image: 'http://127.0.0.1:8000/storage/uploads/products/http://127.0.0.1:8000/images/default/image.jpg'
                          description: 'Est repudiandae enim dolorum.'
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
